import { AboutSlint, Palette } from "std-widgets.slint";

export component AboutPage inherits Window {
    callback back-clicked();
    
    width: 100%;
    height: 100%;
    
    VerticalLayout {
        alignment: end;

        Rectangle {
            height: 112px;
            background: Palette.background.darker(0.25);
            
            HorizontalLayout {
                alignment: space-between;
                               
                AboutSlint { width: 12.5%; }

                HorizontalLayout {
                    padding: 16px;
                    spacing: 4px;

                    Image { source: @image-url("./assets/cc.svg"); }
                    Image { source: @image-url("./assets/by.svg"); }
                    Image { source: @image-url("./assets/nc.svg"); }
                    Image { source: @image-url("./assets/sa.svg"); }
                }
            }
        }
    }
}
