import { AboutSlint, Palette, Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component AboutPage inherits Window {
    callback back-clicked();
    
    width: 100%;
    height: 100%;

    VerticalLayout {
        alignment: start;

        HorizontalBox {
            Button {
                colorize-icon: true;
                icon: @image-url("./assets/icons/arrow-left-solid.svg");
                clicked => { back-clicked(); }
            }
        }
    }
            
    VerticalLayout {
        alignment: end;

        Rectangle {
            height: 112px;
            background: Palette.background.darker(0.25);
            
            HorizontalLayout {
                alignment: space-between;
                               
                AboutSlint {}

                HorizontalLayout {
                    padding: 16px;
                    spacing: 4px;

                    Image { source: @image-url("./assets/images/cc.svg"); }
                    Image { source: @image-url("./assets/images/by.svg"); }
                    Image { source: @image-url("./assets/images/nc.svg"); }
                    Image { source: @image-url("./assets/images/sa.svg"); }
                }
            }
        }
    }
}
