import { MenuPage, AboutPage, PageType } from "./pages.slint";

export component MainWindow inherits Window {
    in-out property <string> env-name;
    in-out property <string> env-description;
    in-out property <string> env-version;

    property <PageType> current-page: MenuPage;

    title: "algor";

    MenuPage {
        visible: current-page == PageType.MenuPage;
        about-clicked => { current-page = PageType.AboutPage }
    }
    AboutPage {
        env-name: env-name;
        env-version: env-version;
        env-description: env-description;

        visible: current-page == PageType.AboutPage;
        back-clicked => { current-page = PageType.MenuPage; }
    }
}
