import { MenuPage, AboutPage, PageType } from "./pages.slint";

export component MainWindow inherits Window {
    property <PageType> current-page: MenuPage;
    title: "algor";

    MenuPage {
        visible: current-page == PageType.MenuPage;
        about-clicked => { current-page = PageType.AboutPage }
    }
    AboutPage {
        visible: current-page == PageType.AboutPage;
        back-clicked => { current-page = PageType.MenuPage; }
    }
}
